spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter


        - id: tasks-service
          uri: lb://tasks-service
          predicates:
            - Path=/tasks/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**



