spring:
  application:
    name: project-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/project_database
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

task:
  service:
    url: http://localhost:8081
