spring:
  application:
    name: tasks-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/task_database
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

